# Permalinks
#
permalink:           pretty

# Setup
title:               Paul J. Andrew
tagline:             ┬─┬﻿ ノ( ゜-゜ノ)
description:         "Hi there! I'm a freelance web developer based in Mexico City."
url:                 http://pauljandrew.github.io/
paginate:            1
baseurl:             ""
title_image:         pja.io/public/profile.jpeg


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Paul J. Andrew
  email:             paul@pja.io
  twitter:           https://twitter.com/paujaman
  twitter_username:    paujaman
  linkedin:          https://linkedin.com/in/pauljandrew
  github:            https://github.com/pauljandrew

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/pauljandrew/pauljandrew.github.io
