# Permalinks
#
permalink:           pretty

# Setup
title:               Paul J. Andrew
tagline:             pja.io
description:         "Hello! I'm a freelance web developer based in Mexico City."
url:                 http://pauljandrew.github.io/
paginate:            1
baseurl:             ""
title_image:         http://pja.io/public/profile.jpeg


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Paul J. Andrew
  email:             paul@pja.io
  twitter:           https://twitter.com/paujaman
  twitter_username:  paujaman
  linkedin:          https://linkedin.com/in/pauljandrew
  github:            https://github.com/pauljandrew
  stackoverflow:     https://stackoverflow.com/users/389790/paul-andrew

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/pauljandrew/pauljandrew.github.io

plugins: [jekyll-paginate]